# Generated by Django 4.2.5 on 2023-10-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0005_remove_mymodel_field1_remove_mymodel_field10_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='activity_category',
            new_name='activitycategory',
        ),
    ]
