# Generated by Django 4.2.5 on 2023-10-19 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0006_rename_activity_category_mymodel_activitycategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='activity_type',
            new_name='activitytype',
        ),
    ]
